# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: next.js to ec2

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    env:
      working-directory: /home/ubuntu/code/demo2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn
      - run: yarn build
      - run: pm2 delete app-name
      - run: pm2 start npm --name app-name -- start
